name: Empty Commit

on:
  schedule:
    - cron: '0 0 * * *' # runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  Commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v2


      - name: Commit
        run: |
          git config --global user.email ${{ secrets.EMAIL_GIT }} 
          git config --global user.name ${{ secrets.USERNAME_GIT }}
          git commit --allow-empty -m "Plant a grass!!!"
          git push origin main
